#! /usr/bin/env python

from collections import OrderedDict 

sample = {
    'data_obs' : {
        'order' : 0,
        'files' : [],
        'fillcolor' : 0,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Data",
        'weight': 1.,
        'plot': True,
    },
    'DY' : {
        'order' : 1,
        'files' : [],
        'fillcolor' : 8,
        'fillstyle' : 1001,
        'linecolor' : 8,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z #rightarrow ll + jets",
        'weight': 1.,
        'plot': True,
    },
    'ZToNuNu' : {
        'order' : 1,
        'files' : [],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z #rightarrow #nu#nu + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJets' : {
        'order' : 2,
        'files' : [],
        'fillcolor' : 834,
        'fillstyle' : 1001,
        'linecolor' : 834,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W #rightarrow l#nu + jets",
        'weight': 1.,
        'plot': True,
    },
    'TT' : {
        'order' : 3,
        'files' : [],
        'fillcolor' : 618,
        'fillstyle' : 1001,
        'linecolor' : 618,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}",
        'weight': 1.,
        'plot': True,
    },
    'SingleTop' : {
        'order' : 4,
        'files' : [],
        'fillcolor' : 798,
        'fillstyle' : 1001,
        'linecolor' : 798,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "single t",
        'weight': 1.,
        'plot': True,
    },
    'otherBkg' : {
        'order' : 5,
        'files' : [],
        'fillcolor' : 619,
        'fillstyle' : 1001,
        'linecolor' : 619,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "other",
        'weight': 1.,
        'plot': True,
    },
    'QCD' : {
        'order' : 6,
        'files' : [],
        'fillcolor' : 602,
        'fillstyle' : 1001,
        'linecolor' : 602,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "QCD",
        'weight': 1.,
        'plot': True,
    },
    
    'AllBkg' : {
        'order' : 99,
        'files' : [],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "all backgrounds",
        'weight': 1.,
        'plot': True,
    },
    


#################### ttDM scalar

    'DMtt_sc_Mchi1Mphi10' : {
        'order' : 1001,
        'files' : [],
        'fillcolor' : 0,
        'fillstyle' : 0,
        'linecolor' : 632,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "ttDM m_{#Phi}=10 GeV m_{#Chi}=1 GeV",
        'weight': 1.,
        'plot': False,
    },

    # Dummy entry for background sum
    'BkgSum' : {
        'order' : 0,
        'files' : [],
        'fillcolor' : 1,
        'fillstyle' : 3003,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "MC Stat",
        'weight': 1.,
        'plot': True,
    },
}


